// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-8VrffIyo_NKsx6XkDO4KTyd2tYxmxU',
    appId: '1:1052812706021:web:3c213eadbb4c144241d40c',
    messagingSenderId: '1052812706021',
    projectId: 'quizapp-956f3',
    authDomain: 'quizapp-956f3.firebaseapp.com',
    storageBucket: 'quizapp-956f3.appspot.com',
    measurementId: 'G-D7BSMN7K9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVv00AB0MF6aDC_XJaito_lTkj6LRXN1Y',
    appId: '1:1052812706021:android:ac9e1e3b1638eb5b41d40c',
    messagingSenderId: '1052812706021',
    projectId: 'quizapp-956f3',
    storageBucket: 'quizapp-956f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYjGWAhc2WEBXzPIcNuDlPTlGghrLJdw',
    appId: '1:1052812706021:ios:e2ac16caf19fd95e41d40c',
    messagingSenderId: '1052812706021',
    projectId: 'quizapp-956f3',
    storageBucket: 'quizapp-956f3.appspot.com',
    iosBundleId: 'com.example.assignmentZarityHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYjGWAhc2WEBXzPIcNuDlPTlGghrLJdw',
    appId: '1:1052812706021:ios:e2ac16caf19fd95e41d40c',
    messagingSenderId: '1052812706021',
    projectId: 'quizapp-956f3',
    storageBucket: 'quizapp-956f3.appspot.com',
    iosBundleId: 'com.example.assignmentZarityHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI-8VrffIyo_NKsx6XkDO4KTyd2tYxmxU',
    appId: '1:1052812706021:web:b27769d2d95bbd0341d40c',
    messagingSenderId: '1052812706021',
    projectId: 'quizapp-956f3',
    authDomain: 'quizapp-956f3.firebaseapp.com',
    storageBucket: 'quizapp-956f3.appspot.com',
    measurementId: 'G-2BHW3Q25T9',
  );
}
